import { useState } from 'react'
import { ArrowUpRight, CalendarDays, CheckCheck, CirclePlus, Layers, Sprout, Users, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useActivity, useOverview, useUsers } from '@/lib/queries'
import { date, initials, number } from '@/lib/utils'
import { ErrorState, LoadingCards, TextLink, EmptyState } from '@/components/feedback'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import type { Overview } from '@/lib/types'

const metrics = [
  { key: 'total_users', label: 'Total users', note: 'Your Flow community', icon: Users, color: 'bg-[#eef0fc] text-[#686dae]' },
  { key: 'active_users_7d', label: 'Active users', note: 'Completed a task in 7 days', icon: Zap, color: 'bg-[#fcf3df] text-[#b48a37]' },
  { key: 'tasks_created_today', label: 'Tasks created', note: 'Created today', icon: CirclePlus, color: 'bg-[#edf4fb] text-[#5c87b3]' },
  { key: 'tasks_completed_today', label: 'Tasks completed', note: 'Completed today', icon: CheckCheck, color: 'bg-[#e8f3ed] text-[#388d6c]' },
  { key: 'routines_run_today', label: 'Routines completed', note: 'Full runs finished today', icon: Layers, color: 'bg-[#f5eef8] text-[#9971b0]' },
] as const
function Metrics({ data }: { data: Overview }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(({ key, label, note, icon: Icon, color }) => <Card key={key} className="p-5"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-muted-foreground">{label}</p><span className={`rounded-lg p-1.5 ${color}`}><Icon size={16}/></span></div><p className="mt-5 text-[32px] font-semibold leading-none tracking-[-.05em] tabular-nums">{number(data[key])}</p><p className="mt-3 text-[10px] text-muted-foreground">{note}</p></Card>)}</div> }
export function OverviewPage() {
  const [days, setDays] = useState(14)
  const overview = useOverview()
  const activity = useActivity(days)
  const users = useUsers('', 'all', 0, 5)
  const completions = activity.data?.reduce((sum, point) => sum + point.tasks_completed, 0) ?? 0
  return <div className="page-enter space-y-7">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mb-2 flex items-center gap-1.5 text-[11px] font-medium text-primary"><Sprout size={14}/>THE BIG PICTURE</div><h1 className="page-heading">Workspace overview</h1><p className="mt-2 text-sm text-muted-foreground">A clear view of the people and progress behind Flow.</p></div>{overview.data && <div className="flex items-center gap-2.5 rounded-lg border bg-card px-3.5 py-2.5 text-xs"><CalendarDays size={15} className="text-muted-foreground"/>{date(`${overview.data.date}T12:00:00`)}<span className="border-l pl-2.5 text-[10px] text-muted-foreground">{overview.data.timezone.split('/').pop()}</span></div>}</div>
    {overview.isPending ? <LoadingCards/> : overview.error ? <ErrorState error={overview.error} retry={() => overview.refetch()}/> : <Metrics data={overview.data}/>}
    <div className="grid gap-5 xl:grid-cols-[1fr_300px]">
      <Card><CardHeader className="flex-row items-start justify-between gap-3 space-y-0"><div><CardTitle>Progress over time</CardTitle><CardDescription className="mt-1.5">Every completed task is a step forward.</CardDescription></div><label className="shrink-0"><span className="sr-only">Activity period</span><select value={days} onChange={event => setDays(Number(event.target.value))} className="rounded-md border bg-card px-2.5 py-2 text-xs"><option value={7}>Last 7 days</option><option value={14}>Last 14 days</option><option value={30}>Last 30 days</option></select></label></CardHeader><CardContent>
        {activity.error ? <ErrorState error={activity.error} retry={() => activity.refetch()}/> : activity.isPending ? <div role="status" aria-label="Loading activity" className="h-[260px] animate-pulse rounded-lg bg-muted"/> : <><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div className="flex items-baseline gap-2"><span className="text-[30px] font-semibold tracking-tight tabular-nums">{number(completions)}</span><span className="text-xs text-muted-foreground">tasks completed this period</span></div><div className="flex items-center gap-4 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-primary"/>Completed</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#bacbc2]"/>Created</span></div></div><div className="h-[236px] w-full" role="img" aria-label={`Tasks created and completed over the last ${days} days. ${completions} tasks completed.`}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={activity.data} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><defs><linearGradient id="flowChartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#147d64" stopOpacity={.16}/><stop offset="100%" stopColor="#147d64" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0ed" strokeDasharray="3 3"/><XAxis dataKey="date" tickFormatter={value => date(value + 'T12:00:00', { month: 'short', day: 'numeric' })} tick={{ fontSize: 10, fill: '#849087' }} tickLine={false} axisLine={false} minTickGap={35} dy={10}/><YAxis allowDecimals={false} tick={{ fontSize: 10, fill: '#849087' }} tickLine={false} axisLine={false} domain={[0, 'auto']}/><Tooltip contentStyle={{ borderRadius: 10, border: '1px solid #e5eae6', fontSize: 12, boxShadow: '0 6px 20px #17382a0d' }} labelFormatter={label => date(label + 'T12:00:00')}/><Area type="monotone" dataKey="tasks_completed" name="Completed" stroke="#147d64" strokeWidth={2.5} fill="url(#flowChartFill)" isAnimationActive={false}/><Line type="monotone" dataKey="tasks_created" name="Created" stroke="#bacbc2" strokeWidth={1.5} strokeDasharray="5 4" dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><details className="mt-5 text-xs text-muted-foreground"><summary className="w-fit cursor-pointer hover:text-primary">View chart data</summary><div className="mt-3 max-h-48 overflow-auto"><table className="w-full text-left"><caption className="sr-only">Daily task activity</caption><thead><tr><th className="p-2">Date</th><th>Created</th><th>Completed</th></tr></thead><tbody>{activity.data.map(point => <tr key={point.date} className="border-t"><td className="p-2">{point.date}</td><td>{number(point.tasks_created)}</td><td>{number(point.tasks_completed)}</td></tr>)}</tbody></table></div></details></>}
      </CardContent></Card>
      <div className="flex flex-col gap-5"><Card className="relative overflow-hidden border-[#d9e8dd] bg-[#edf5ee] p-6"><span className="mb-6 flex size-10 items-center justify-center rounded-xl border border-[#d6e6d9] bg-white/60 text-primary"><Sprout size={21}/></span><p className="text-lg font-medium leading-7 tracking-tight">Small steps.<br/>Meaningful progress.</p><p className="mt-3 text-xs leading-6 text-[#5e7b68]">Flow helps people make room for what matters. This is where you help it happen.</p><Link to="/users" className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-primary">Meet your community<ArrowUpRight size={15}/></Link><div aria-hidden="true" className="absolute -right-8 -top-8 size-32 rounded-full border-[18px] border-white/25"/></Card><Card className="flex-1 p-5"><p className="eyebrow">About these numbers</p><p className="mt-3 text-xs leading-6 text-muted-foreground">Active users have completed at least one task in the last seven days. Routine totals count fully completed runs.</p>{overview.data && <p className="mt-3 text-[10px] text-muted-foreground">Daily reporting · {overview.data.timezone}</p>}</Card></div>
    </div>
    <Card><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle>New faces at Flow</CardTitle><CardDescription className="mt-1.5">The latest people to join your community.</CardDescription></div><Link to="/users"><TextLink>View all users</TextLink></Link></CardHeader>{users.error ? <div className="p-5"><ErrorState error={users.error} retry={() => users.refetch()}/></div> : users.isPending ? <div role="status" aria-label="Loading users" className="mx-6 mb-6 h-40 animate-pulse rounded-lg bg-muted"/> : users.data.items.length === 0 ? <EmptyState title="Your community starts here" description="New Flow accounts will appear here as people join."/> : <div className="overflow-x-auto"><table className="w-full whitespace-nowrap"><caption className="sr-only">Recently registered users</caption><thead className="border-y bg-muted/50"><tr><th className="table-head">User</th><th className="table-head">Joined</th><th className="table-head">Tasks</th><th className="table-head">Account</th></tr></thead><tbody>{users.data.items.map(user => <tr key={user.id} className="border-b last:border-0"><td className="table-cell"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-[#eeeae3] text-[11px] font-semibold text-[#817260]">{initials(user.display_name)}</span><div><p className="text-xs font-medium">{user.display_name}</p><p className="mt-1 text-[11px] text-muted-foreground">{user.email}</p></div></div></td><td className="table-cell text-xs text-muted-foreground">{date(user.created_at)}</td><td className="table-cell text-xs tabular-nums">{number(user.task_count)}</td><td className="table-cell"><Badge tone={user.is_active ? 'good' : 'neutral'}><span className={`size-1 rounded-full ${user.is_active ? 'bg-emerald-500' : 'bg-slate-400'}`}/>{user.is_active ? 'Active' : 'Deactivated'}</Badge></td></tr>)}</tbody></table></div>}</Card>
  </div>
}
