import { useEffect, useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { useSearchParams } from 'react-router-dom'
import { ChevronLeft, ChevronRight, Download, Loader2, MoreHorizontal, Search, ShieldCheck, UserRound, UserRoundX, X } from 'lucide-react'
import { api, queryClient } from '@/lib/api'
import { useUsers } from '@/lib/queries'
import type { AdminUser } from '@/lib/types'
import { cn, date, initials, number } from '@/lib/utils'
import { EmptyState, ErrorState } from '@/components/feedback'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog'
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogTitle } from '@/components/ui/alert-dialog'

function exportPage(users: AdminUser[]) {
  const cell = (value: unknown) => `"${String(value).replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`
  const rows = [['Name', 'Email', 'Status', 'Tasks', 'Completed tasks', 'Routines', 'Joined'], ...users.map(user => [user.display_name, user.email, user.is_active ? 'active' : 'inactive', user.task_count, user.completed_task_count, user.routine_count, user.created_at])]
  const url = URL.createObjectURL(new Blob([rows.map(row => row.map(cell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8;' }))
  const link = document.createElement('a'); link.href = url; link.download = 'flow-users-page.csv'; link.click(); URL.revokeObjectURL(url)
}
export function UsersPage() {
  const [params, setParams] = useSearchParams()
  const [search, setSearch] = useState(params.get('search') || '')
  const filter = ['active', 'inactive'].includes(params.get('status') || '') ? params.get('status')! : 'all'
  const offset = Math.max(0, Number(params.get('offset')) || 0)
  const [selected, setSelected] = useState<AdminUser | null>(null)
  const [confirm, setConfirm] = useState<AdminUser | null>(null)
  const [notice, setNotice] = useState('')
  const users = useUsers(params.get('search') || '', filter, offset)
  useEffect(() => {
    const timer = setTimeout(() => { if (search !== (params.get('search') || '')) setParams({ search, status: filter, offset: '0' }, { replace: true }) }, 300)
    return () => clearTimeout(timer)
  }, [search, params, setParams, filter])
  const deactivate = useMutation({ mutationFn: (user: AdminUser) => api(`/admin/users/${user.id}/deactivate`, { method: 'POST' }), onSuccess: (_, user) => {
    setConfirm(null); setSelected(null); setParams({ search, status: filter, offset: '0' }); setNotice(`${user.display_name} has been deactivated.`)
    queryClient.invalidateQueries({ queryKey: ['users'] }); queryClient.invalidateQueries({ queryKey: ['overview'] })
  } })
  function changeFilter(value: string) { setParams({ search, status: value, offset: '0' }) }
  return <div className="page-enter space-y-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow mb-2 text-primary">Your community</p><h1 className="page-heading">People at Flow</h1><p className="mt-2 text-sm text-muted-foreground">A little care for the people making progress every day.</p></div><Button variant="outline" disabled={!users.data?.items.length} onClick={() => exportPage(users.data!.items)}><Download/>Export this page</Button></div>
    {notice && <div role="status" className="flex items-center justify-between gap-3 rounded-lg border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-primary">{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')} className="rounded p-1"><X size={15}/></button></div>}
    <Card><div className="flex flex-wrap items-center justify-between gap-4 border-b p-5"><div className="flex items-center gap-1 rounded-lg bg-muted p-1" aria-label="Filter accounts">{[{ value: 'all', label: 'All users' }, { value: 'active', label: 'Active' }, { value: 'inactive', label: 'Deactivated' }].map(item => <button key={item.value} onClick={() => changeFilter(item.value)} aria-pressed={filter === item.value} className={cn('rounded-md px-3 py-2 text-xs font-medium transition-colors', filter === item.value ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground')}>{item.label}{item.value === 'all' && filter === 'all' && users.data && <span className="ml-2 rounded bg-muted px-1.5 py-0.5 text-[10px]">{number(users.data.total)}</span>}</button>)}</div><div className="relative w-full sm:w-64"><Search size={15} className="absolute left-3 top-3 text-muted-foreground"/><Input aria-label="Search users by name or email" placeholder="Search name or email…" className="h-10 pl-9" value={search} onChange={event => setSearch(event.target.value)}/></div></div>
    {users.error ? <div className="p-6"><ErrorState error={users.error} retry={() => users.refetch()}/></div> : users.isPending ? <div role="status" aria-label="Loading users" className="space-y-5 p-6">{Array.from({ length: 5 }, (_, i) => <div key={i} className="h-12 animate-pulse rounded bg-muted"/>)}</div> : users.data.items.length === 0 ? <EmptyState title={search ? 'No matching people' : 'No users here yet'} description={search ? 'Try a different name or email address, or choose another account filter.' : 'Accounts will appear here when people join Flow.'}/> : <div className="overflow-x-auto"><table className="w-full whitespace-nowrap"><caption className="sr-only">Flow user accounts and activity counts</caption><thead className="border-b bg-muted/40"><tr>{['User', 'Account', 'Tasks', 'Routines', 'Joined', ''].map((title, i) => <th key={i} className="table-head">{title || <span className="sr-only">Actions</span>}</th>)}</tr></thead><tbody>{users.data.items.map(user => <tr key={user.id} className="border-b transition-colors last:border-0 hover:bg-muted/30"><td className="table-cell"><button className="flex items-center gap-3 rounded text-left" onClick={() => setSelected(user)}><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-[#edf1eb] text-xs font-semibold text-[#66805d]">{initials(user.display_name)}</span><span><span className="flex items-center gap-2 text-xs font-medium">{user.display_name}{user.is_staff && <ShieldCheck size={12} className="text-primary" aria-label="Staff account"/>}</span><span className="mt-1 block text-[11px] text-muted-foreground">{user.email}</span></span></button></td><td className="table-cell"><Badge tone={user.is_active ? 'good' : 'neutral'}><span className={cn('size-1 rounded-full', user.is_active ? 'bg-emerald-500' : 'bg-slate-400')}/>{user.is_active ? 'Active' : 'Deactivated'}</Badge></td><td className="table-cell"><p className="text-xs tabular-nums">{number(user.task_count)}</p><p className="mt-1 text-[10px] text-muted-foreground">{number(user.completed_task_count)} completed</p></td><td className="table-cell text-xs tabular-nums">{number(user.routine_count)}</td><td className="table-cell text-xs text-muted-foreground">{date(user.created_at)}</td><td className="table-cell"><Button variant="ghost" size="icon" className="size-8" aria-label={`View ${user.display_name}`} onClick={() => setSelected(user)}><MoreHorizontal/></Button></td></tr>)}</tbody></table></div>}
    {users.data && <div className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4"><p className="text-[11px] text-muted-foreground">{users.data.total ? `${number(offset + 1)}–${number(Math.min(offset + 20, users.data.total))} of ${number(users.data.total)} users` : '0 users'}</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={offset === 0 || users.isFetching} onClick={() => setParams({ search, status: filter, offset: String(Math.max(0, offset - 20)) })}><ChevronLeft/>Previous</Button><Button variant="outline" size="sm" disabled={offset + 20 >= users.data.total || users.isFetching} onClick={() => setParams({ search, status: filter, offset: String(offset + 20) })}>Next<ChevronRight/></Button></div></div>}
    </Card><div className="flex items-start gap-2 text-[11px] leading-5 text-muted-foreground"><ShieldCheck size={14} className="mt-0.5 shrink-0"/>This view shows account information and activity counts. Personal task and routine content stays private.</div>
    <Dialog open={!!selected} onOpenChange={open => !open && setSelected(null)}><DialogContent><DialogTitle className="flex items-center gap-2 text-lg font-semibold"><UserRound size={18}/>Account details</DialogTitle><DialogDescription className="text-sm text-muted-foreground">Basic information and activity at a glance.</DialogDescription>{selected && <><div className="rounded-lg bg-muted p-4"><p className="font-medium">{selected.display_name}</p><p className="mt-1 break-all text-sm text-muted-foreground">{selected.email}</p><div className="mt-3 flex gap-2"><Badge tone={selected.is_active ? 'good' : 'neutral'}>{selected.is_active ? 'Active' : 'Deactivated'}</Badge>{selected.is_staff && <Badge>Staff</Badge>}<Badge>{selected.is_verified ? 'Email verified' : 'Email unverified'}</Badge></div></div><dl className="grid grid-cols-3 gap-3 text-center">{[['Tasks', selected.task_count], ['Completed', selected.completed_task_count], ['Routines', selected.routine_count]].map(([label, value]) => <div key={label}><dd className="text-2xl font-semibold tabular-nums">{number(Number(value))}</dd><dt className="mt-1 text-[11px] text-muted-foreground">{label}</dt></div>)}</dl><p className="text-xs text-muted-foreground">Joined {date(selected.created_at)}</p>{selected.is_staff ? <p className="rounded-md bg-secondary p-3 text-xs text-primary">Staff accounts are protected from deactivation here.</p> : selected.is_active && <Button variant="outline" className="text-destructive hover:bg-rose-50 hover:text-destructive" onClick={() => { setConfirm(selected); setSelected(null); deactivate.reset() }}><UserRoundX/>Deactivate account</Button>}</>}</DialogContent></Dialog>
    <AlertDialog open={!!confirm} onOpenChange={open => { if (!open && !deactivate.isPending) setConfirm(null) }}><AlertDialogContent><span className="inline-flex rounded-xl bg-rose-50 p-3 text-destructive"><UserRoundX size={22}/></span><AlertDialogTitle className="text-lg font-semibold">Deactivate {confirm?.display_name}?</AlertDialogTitle><AlertDialogDescription className="text-sm leading-6 text-muted-foreground">They will be signed out and won’t be able to sign in. Their tasks, routines, and account data will stay intact.</AlertDialogDescription>{deactivate.error && <p role="alert" className="text-sm text-destructive">{deactivate.error.message}</p>}<div className="flex justify-end gap-3"><AlertDialogCancel asChild><Button variant="outline" disabled={deactivate.isPending}>Keep account</Button></AlertDialogCancel><Button variant="destructive" disabled={deactivate.isPending} onClick={() => confirm && deactivate.mutate(confirm)}>{deactivate.isPending && <Loader2 className="animate-spin"/>}Deactivate</Button></div></AlertDialogContent></AlertDialog>
  </div>
}
