import { AlertCircle, ArrowRight, Inbox, RefreshCw, Waves } from 'lucide-react'
import { Button } from './ui/button'
import { ApiError } from '@/lib/api'
import { cn } from '@/lib/utils'

export function Brand({ inverse = false }: { inverse?: boolean }) { return <span className={cn('inline-flex items-center gap-2.5 text-[25px] font-semibold tracking-[-.05em]', inverse && 'text-white')}><span className={cn('flex size-9 items-center justify-center rounded-xl bg-primary text-white', inverse && 'bg-white/15')}><Waves size={24} strokeWidth={2.5}/></span>flow<span className={cn('ml-1 mt-1 rounded border px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-[.09em]', inverse ? 'border-white/20 text-white/65' : 'text-muted-foreground')}>operations</span></span> }
export function ErrorState({ error, retry }: { error: Error; retry?: () => void }) { return <div role="alert" className="flex flex-wrap items-center gap-4 rounded-xl border border-rose-100 bg-rose-50/60 p-5"><AlertCircle className="size-5 shrink-0 text-rose-600"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">Something needs another try</p><p className="mt-1 text-sm text-muted-foreground">{error.message}</p>{error instanceof ApiError && error.requestId && <p className="mt-1 text-xs text-muted-foreground">Reference: {error.requestId}</p>}</div>{retry && <Button variant="outline" size="sm" onClick={retry}><RefreshCw/>Try again</Button>}</div> }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="flex flex-col items-center px-6 py-14 text-center"><span className="mb-4 rounded-2xl bg-muted p-3"><Inbox className="size-6 text-muted-foreground"/></span><h3 className="font-medium">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p></div> }
export function LoadingCards() { return <div role="status" aria-label="Loading workspace" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Array.from({ length: 5 }, (_, i) => <div key={i} className="h-40 animate-pulse rounded-xl border bg-card p-5"><div className="h-3 w-2/3 rounded bg-muted"/><div className="mt-7 h-8 w-1/2 rounded bg-muted"/></div>)}</div> }
export function TextLink({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-1.5 text-xs font-medium text-primary">{children}<ArrowRight size={14}/></span> }
