"""Accounts, manual routine runs, notification outboxes and operations.

Revision ID: 0002_hardening
Revises: 0001_initial
"""

import sqlalchemy as sa

from alembic import op

revision = "0002_hardening"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade():
    # Both the original migration (VARCHAR) and development create_all (native
    # PostgreSQL ENUMs) converge on the same portable enum representation.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TABLE tasks ALTER COLUMN status TYPE VARCHAR(20) USING status::text")
        op.execute("ALTER TABLE tasks ALTER COLUMN priority TYPE VARCHAR(20) USING priority::text")
    op.execute("UPDATE tasks SET status = upper(status), priority = upper(priority)")
    for table in ("users", "tasks", "routines", "reminders"):
        with op.batch_alter_table(table) as batch:
            batch.alter_column(
                "created_at", existing_type=sa.DateTime(timezone=True), server_default=sa.func.now()
            )
    with op.batch_alter_table("tasks") as batch:
        batch.alter_column(
            "updated_at", existing_type=sa.DateTime(timezone=True), server_default=sa.func.now()
        )
    for table, column, default in (
        ("users", "is_active", sa.true()),
        ("routines", "is_active", sa.true()),
        ("reminders", "is_sent", sa.false()),
    ):
        with op.batch_alter_table(table) as batch:
            batch.alter_column(column, existing_type=sa.Boolean(), server_default=default)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_emails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_id", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_emails")),
    )
    with op.batch_alter_table("outbound_emails", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outbound_emails_status"), ["status"], unique=False)

    op.create_table(
        "account_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_account_tokens_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_account_tokens_token_hash")),
    )
    with op.batch_alter_table("account_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_tokens_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_account_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "admin_audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name="fk_admin_audit_actor_users"),
        sa.ForeignKeyConstraint(["target_id"], ["users.id"], name="fk_admin_audit_target_users"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_audit")),
    )
    with op.batch_alter_table("admin_audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_audit_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_admin_audit_target_id"), ["target_id"], unique=False)

    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=4096), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_devices_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("token", name=op.f("uq_devices_token")),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_refresh_tokens_auth_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "routine_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("routine_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
            name=op.f("fk_routine_runs_routines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_routine_runs_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_runs")),
        sa.UniqueConstraint("user_id", "idempotency_key", name=op.f("uq_routine_runs_user_id")),
    )
    with op.batch_alter_table("routine_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_routine_runs_completed_at"), ["completed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_routine_runs_routine_id"), ["routine_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_routine_runs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "routine_run_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=280), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("offset_minutes", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["routine_runs.id"],
            name=op.f("fk_routine_run_steps_routine_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_run_steps")),
    )
    with op.batch_alter_table("routine_run_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_routine_run_steps_run_id"), ["run_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=280), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
            name=op.f("fk_notifications_reminders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("reminder_id", name=op.f("uq_notifications_reminder_id")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "push_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_id", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_push_deliveries_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_push_deliveries_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_deliveries")),
        sa.UniqueConstraint(
            "notification_id", "device_id", name=op.f("uq_push_deliveries_notification_id")
        ),
    )
    with op.batch_alter_table("push_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_push_deliveries_next_attempt_at"), ["next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_push_deliveries_status"), ["status"], unique=False)

    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            "ix_reminders_due_pending", ["is_sent", "cancelled_at", "remind_at"], unique=False
        )
        batch_op.drop_constraint(batch_op.f("fk_reminders_tasks"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_reminders_tasks"), "tasks", ["task_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("routine_steps", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_routine_steps_routines"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_routine_steps_routines"),
            "routines",
            ["routine_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_user_completed", ["user_id", "completed_at"], unique=False)
        batch_op.create_index("ix_tasks_user_due", ["user_id", "due_date"], unique=False)
        batch_op.drop_constraint(batch_op.f("fk_tasks_task_categories"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_tasks_task_categories"),
            "task_categories",
            ["category_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_staff", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_verified", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("timezone", sa.String(length=64), server_default="Asia/Kabul", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    for table in ("users", "tasks", "routines", "reminders"):
        with op.batch_alter_table(table) as batch:
            batch.alter_column(
                "created_at", existing_type=sa.DateTime(timezone=True), server_default=None
            )
    with op.batch_alter_table("tasks") as batch:
        batch.alter_column(
            "updated_at", existing_type=sa.DateTime(timezone=True), server_default=None
        )
    for table, column in (
        ("users", "is_active"),
        ("routines", "is_active"),
        ("reminders", "is_sent"),
    ):
        with op.batch_alter_table(table) as batch:
            batch.alter_column(column, existing_type=sa.Boolean(), server_default=None)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("timezone")
        batch_op.drop_column("is_verified")
        batch_op.drop_column("is_staff")

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_tasks_task_categories"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_tasks_task_categories"), "task_categories", ["category_id"], ["id"]
        )
        batch_op.drop_index("ix_tasks_user_due")
        batch_op.drop_index("ix_tasks_user_completed")

    with op.batch_alter_table("routine_steps", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_routine_steps_routines"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_routine_steps_routines"), "routines", ["routine_id"], ["id"]
        )

    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_reminders_tasks"), type_="foreignkey")
        batch_op.create_foreign_key(batch_op.f("fk_reminders_tasks"), "tasks", ["task_id"], ["id"])
        batch_op.drop_index("ix_reminders_due_pending")
        batch_op.drop_column("sent_at")
        batch_op.drop_column("cancelled_at")

    with op.batch_alter_table("push_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_push_deliveries_status"))
        batch_op.drop_index(batch_op.f("ix_push_deliveries_next_attempt_at"))

    op.drop_table("push_deliveries")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("routine_run_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routine_run_steps_run_id"))

    op.drop_table("routine_run_steps")
    with op.batch_alter_table("routine_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routine_runs_user_id"))
        batch_op.drop_index(batch_op.f("ix_routine_runs_routine_id"))
        batch_op.drop_index(batch_op.f("ix_routine_runs_completed_at"))

    op.drop_table("routine_runs")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_session_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_expires_at"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))

    op.drop_table("devices")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("admin_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_audit_target_id"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_actor_id"))

    op.drop_table("admin_audit")
    with op.batch_alter_table("account_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_account_tokens_expires_at"))

    op.drop_table("account_tokens")
    with op.batch_alter_table("outbound_emails", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbound_emails_status"))

    op.drop_table("outbound_emails")
    # ### end Alembic commands ###
